sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t BenPVandenberg/Discord-Bot-Admin -f Dockerfile.dev .

script:
  - docker run -e CI=true BenPVandenberg/Discord-Bot-Admin npm run test
