version: '3.3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: benpv/discord-bot
    container_name: discordbot
    command: npm start
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
